id: A9AF95478
title: A Concise Sang Offering to Tārā
type: translation
pechas:
- I788F8799
- ID3D9C184
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:53.683192
  last_modified_at: 2023-01-04 12:45:53.683207
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I788F8799/6BBB: '5517'
  ID3D9C184/9DC9: '5517'
